import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {type FormEvent,useState} from 'react';
import {endpoints} from '../api/queries';
import {ErrorState,Loading,PageHeader} from '../components/common';
import {REPORT_TYPE_LABELS,type ReportType} from '../reporting';

const domainLabels:Record<string,string>={
  'DEA-D1':'D1 · 수집 및 변환','DEA-D2':'D2 · 데이터 저장소','DEA-D3':'D3 · 운영 및 지원','DEA-D4':'D4 · 보안 및 거버넌스','DEA-UNCLASSIFIED':'미분류'
};
const dashboardLabels:Record<string,string>={questions:'전체 문제',verified:'검증 완료',needs_review:'검토 필요',reports:'미처리 신고'};

export function Admin(){
  return <AdminContent/>;
}

function AdminContent(){
  const client=useQueryClient();
  const [username,setUsername]=useState('');const [password,setPassword]=useState('');
  const dash=useQuery({queryKey:['admin-dashboard'],queryFn:endpoints.adminDashboard});
  const report=useQuery({queryKey:['classification-report'],queryFn:endpoints.classificationReport});
  const readiness=useQuery({queryKey:['mock-readiness'],queryFn:endpoints.mockReadiness});
  const unclassified=useQuery({queryKey:['unclassified'],queryFn:endpoints.unclassified});
  const reports=useQuery({queryKey:['admin-reports'],queryFn:endpoints.adminReports});
  const users=useQuery({queryKey:['admin-users'],queryFn:endpoints.users});
  const createUser=useMutation({mutationFn:()=>endpoints.createUser({username,password,role:'user'}),onSuccess:()=>{setUsername('');setPassword('');return client.invalidateQueries({queryKey:['admin-users']})}});
  const toggleUser=useMutation({mutationFn:({id,is_active}:{id:number;is_active:boolean})=>endpoints.updateUser(id,{is_active}),onSuccess:()=>client.invalidateQueries({queryKey:['admin-users']})});
  const submitUser=(event:FormEvent)=>{event.preventDefault();createUser.mutate()};
  const refresh=()=>client.invalidateQueries({queryKey:['unclassified']}).then(()=>client.invalidateQueries({queryKey:['classification-report']})).then(()=>client.invalidateQueries({queryKey:['mock-readiness']}));
  const classify=useMutation({mutationFn:(ids?:number[])=>endpoints.classifyDomains(ids),onSuccess:refresh});
  const manual=useMutation({mutationFn:({id,code}:{id:number;code:string})=>endpoints.setDomain(id,code),onSuccess:refresh});
  return <div className="admin-page"><PageHeader eyebrow="운영 센터" title="관리자 페이지" description="계정을 등록하고 문제 및 단원 분류 상태를 관리합니다."/>
    {dash.isLoading?<Loading/>:dash.isError?<ErrorState error={dash.error}/>:<div className="metrics admin-overview">{Object.entries(dash.data!).map(([key,value])=><article key={key}><small>{dashboardLabels[key]??key}</small><strong>{value.toLocaleString()}</strong></article>)}</div>}
    <section className="panel user-management"><div className="section-title"><h2>계정 관리</h2><span>{users.data?.length??0}명</span></div><form className="inline-user-form" onSubmit={submitUser}><label>아이디<input value={username} onChange={event=>setUsername(event.target.value)} minLength={3} maxLength={64} pattern="[A-Za-z0-9._-]+" autoComplete="off" required/></label><label>임시 비밀번호<input type="password" value={password} onChange={event=>setPassword(event.target.value)} minLength={8} maxLength={128} autoComplete="new-password" required/></label><button className="button" disabled={createUser.isPending}>{createUser.isPending?'등록 중…':'계정 등록'}</button></form>{createUser.isError&&<p className="form-error">{createUser.error.message}</p>}{users.isLoading?<Loading/>:users.isError?<ErrorState error={users.error}/>:<div className="table-wrap admin-responsive-table"><table><thead><tr><th>아이디</th><th>등록일</th><th>최근 로그인</th><th>상태</th><th>작업</th></tr></thead><tbody>{users.data!.map(user=><tr key={user.id}><td data-label="아이디"><b>{user.username}</b></td><td data-label="등록일">{new Date(user.created_at).toLocaleDateString('ko-KR')}</td><td data-label="최근 로그인">{user.last_login_at?new Date(user.last_login_at).toLocaleString('ko-KR'):'—'}</td><td data-label="상태"><span className={`badge ${user.is_active?'success':'danger'}`}>{user.is_active?'사용 중':'비활성'}</span></td><td data-label="작업"><button disabled={toggleUser.isPending} onClick={()=>toggleUser.mutate({id:user.id,is_active:!user.is_active})}>{user.is_active?'비활성화':'활성화'}</button></td></tr>)}</tbody></table></div>}</section>
    <section className="panel"><div className="section-title"><h2>문제 신고</h2><span>{reports.data?.length??0}건</span></div>{reports.isLoading?<Loading/>:reports.isError?<ErrorState error={reports.error}/>:reports.data!.length===0?<p className="muted">접수된 문제 신고가 없습니다.</p>:<div className="table-wrap admin-responsive-table"><table className="admin-reports-table"><thead><tr><th className="report-time">접수 시각</th><th className="report-type">유형</th><th>문제</th><th>신고 내용</th></tr></thead><tbody>{reports.data!.map(item=><tr key={item.id}><td data-label="접수 시각" className="report-time">{new Date(item.created_at).toLocaleString('ko-KR')}</td><td data-label="유형" className="report-type">{REPORT_TYPE_LABELS[item.report_type as ReportType]??item.report_type}</td><td data-label="문제"><b>{item.question_uid}</b><br/><span>{item.question_ko||item.question_en}</span></td><td data-label="신고 내용" className="report-description">{item.description}</td></tr>)}</tbody></table></div>}</section>
    <section className="panel admin-readiness"><div className="section-title"><h2>모의고사 준비도</h2>{readiness.data&&<span className={`badge ${readiness.data.ready?'success':'danger'}`}>{readiness.data.ready?'구성 가능':'문제 부족'}</span>}</div>{readiness.isLoading?<Loading/>:readiness.isError?<ErrorState error={readiness.error}/>:<><p>미분류 활성 문제 {readiness.data!.unclassified}개</p><div className="table-wrap"><table><thead><tr><th>단원</th><th>필요</th><th>사용 가능</th><th>부족</th></tr></thead><tbody>{readiness.data!.domains.map(item=><tr key={item.domain_code}><td>{domainLabels[item.domain_code]}</td><td>{item.required}</td><td>{item.available}</td><td>{item.shortage}</td></tr>)}</tbody></table></div></>}</section>
    <section className="panel admin-domain-counts"><div className="section-title"><h2>단원별 문제 수</h2><span>{report.data?.certification}</span></div>{report.isLoading?<Loading/>:report.isError?<ErrorState error={report.error}/>:<div className="metrics">{Object.entries(report.data!.domain_counts).map(([code,count])=><article key={code}><small>{domainLabels[code]??code}</small><strong>{count}</strong></article>)}</div>}</section>
    <section className="panel admin-unclassified"><div className="section-title"><h2>DEA-UNCLASSIFIED</h2><div className="actions"><span>{unclassified.data?.total??0}개</span><button className="button" disabled={classify.isPending||!unclassified.data?.total} onClick={()=>classify.mutate(undefined)}>전체 AI 분류</button></div></div>{classify.isError&&<ErrorState error={classify.error}/>} {unclassified.isLoading?<Loading/>:unclassified.isError?<ErrorState error={unclassified.error}/>:unclassified.data!.items.length===0?<p className="muted">미분류 문제가 없습니다.</p>:<div className="table-wrap admin-responsive-table"><table><thead><tr><th>ID</th><th>문제</th><th>상태/신뢰도</th><th>분류 근거</th><th>작업</th></tr></thead><tbody>{unclassified.data!.items.map(question=><tr key={question.id}><td data-label="ID">{question.question_uid}</td><td data-label="문제">{question.question_ko||question.question_en}</td><td data-label="상태/신뢰도">{question.classification_status??'대기'}<br/><small>{question.classification_confidence!=null?`${Math.round(question.classification_confidence*100)}%`:'—'}</small></td><td data-label="분류 근거">{question.classification_reason??'아직 분류되지 않음'}</td><td data-label="작업"><div className="actions"><button disabled={classify.isPending} onClick={()=>classify.mutate([question.id])}>AI 분류</button><select aria-label={`${question.question_uid} 단원 직접 지정`} defaultValue="" onChange={event=>event.target.value&&manual.mutate({id:question.id,code:event.target.value})}><option value="">직접 지정</option>{Object.entries(domainLabels).filter(([code])=>code!=='DEA-UNCLASSIFIED').map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></div></td></tr>)}</tbody></table></div>}</section>
  </div>;
}
